# ===============================
# Local MySQL Database
# ===============================
DB_URL=jdbc:mysql://localhost:3306/travelplanner
DB_USERNAME=root
DB_PASSWORD=9483785824

# ===============================
# Local OpenWeather API Key
# ===============================
WEATHER_API_KEY=fb6d375e743ff8e2947c2fc06993b776